# Generated by Django 3.2.5 on 2021-07-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2charm', '0002_user_plots'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_plots',
        ),
    ]
