# Generated by Django 3.2.5 on 2021-07-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2charm', '0003_delete_user_plots'),
    ]

    operations = [
        migrations.CreateModel(
            name='plot_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.UUIDField(unique=True)),
                ('img_path', models.CharField(max_length=2000)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
