from django import forms


class FilterForm(forms.Form):
    CHOICES_initial = [('Bd', '$B^0$'), ('Bu', '$B^+$'), ('B', '$B^0+B^+$'), ('Bs', '$B_s^0$'),
                       ('Bc', '$B_c^+$'), ('Lambdab', '$\\Lambda_b$'), ('Xib', '$\\Xi_b$'), ('Omegab', '$\\Omega_b$')]
    initial = forms.ChoiceField(required=False, label='Initial Particles',
                                choices=CHOICES_initial, widget=forms.RadioSelect(attrs={'class': 'formbtn'}))
    CHOICES_observable = [('BR', 'Branching fraction'), ('ACP', 'CP asymmetry'),
                          ('polarization', 'Polarization')]
    observable = forms.ChoiceField(required=False, label='Type of observable',
                                   choices=CHOICES_observable, widget=forms.RadioSelect(attrs={'class': 'formbtn'}))
    D0 = forms.IntegerField(required=False, label="D0",widget=forms.TextInput())
    Dplus = forms.IntegerField(required=False, label="D+",widget=forms.TextInput())
    Ds = forms.IntegerField(required=False, label="Ds",widget=forms.TextInput())
    Ds0 = forms.IntegerField(required=False, label="D*0",widget=forms.TextInput())
    Dsplus = forms.IntegerField(required=False, label="D*+",widget=forms.TextInput())
    Dss = forms.IntegerField(required=False, label="Ds*",widget=forms.TextInput())
    Dsss = forms.IntegerField(required=False, label="D**",widget=forms.TextInput())
    Dssss = forms.IntegerField(required=False, label="Ds**",widget=forms.TextInput())
    Dssss = forms.IntegerField(required=False, label="Ds**",widget=forms.TextInput())
    Jpsi = forms.IntegerField(required=False, label="Jpsi",widget=forms.TextInput())
    psi2S = forms.IntegerField(required=False, label="psi2S",widget=forms.TextInput())
    etac = forms.IntegerField(required=False, label="etac",widget=forms.TextInput())
    chic = forms.IntegerField(required=False, label="chic",widget=forms.TextInput())
    ccbar = forms.IntegerField(required=False, label="ccbar",widget=forms.TextInput())
    X3872 = forms.IntegerField(required=False, label="X3872",widget=forms.TextInput())
    Pc = forms.IntegerField(required=False, label="Pc",widget=forms.TextInput())
    XYZ = forms.IntegerField(required=False, label="XYZ",widget=forms.TextInput())
    p = forms.IntegerField(required=False, label="p",widget=forms.TextInput())
    n = forms.IntegerField(required=False, label="n",widget=forms.TextInput())
    Lambda = forms.IntegerField(required=False, label="Lambda",widget=forms.TextInput())
    Sigma = forms.IntegerField(required=False, label="Sigma",widget=forms.TextInput())
    Xi = forms.IntegerField(required=False, label="Xi",widget=forms.TextInput())
    Omega = forms.IntegerField(required=False, label="Omega",widget=forms.TextInput())
    baryon = forms.IntegerField(required=False, label="baryon",widget=forms.TextInput())
    Lambdac = forms.IntegerField(required=False, label="Lambdac",widget=forms.TextInput())
    Sigmac = forms.IntegerField(required=False, label="Sigmac",widget=forms.TextInput())
    Xic = forms.IntegerField(required=False, label="Xic",widget=forms.TextInput())
    cbaryon = forms.IntegerField(required=False, label="cbaryon",widget=forms.TextInput())
    K = forms.IntegerField(required=False, label="K",widget=forms.TextInput())
    K0 = forms.IntegerField(required=False, label="K0",widget=forms.TextInput())
    Ksplus = forms.IntegerField(required=False, label="Ksplus",widget=forms.TextInput())
    Ks0 = forms.IntegerField(required=False, label="Ks0",widget=forms.TextInput())
    phi = forms.IntegerField(required=False, label="phi",widget=forms.TextInput())
    kaon = forms.IntegerField(required=False, label="kaon",widget=forms.TextInput())
    pi = forms.IntegerField(required=False, label="pi",widget=forms.TextInput())
    pi0 = forms.IntegerField(required=False, label="pi0",widget=forms.TextInput())
    rhoplus = forms.IntegerField(required=False, label="rhoplus",widget=forms.TextInput())
    rho0 = forms.IntegerField(required=False, label="rho0",widget=forms.TextInput())
    eta = forms.IntegerField(required=False, label="eta",widget=forms.TextInput())
    omega = forms.IntegerField(required=False, label="omega",widget=forms.TextInput())
    light = forms.IntegerField(required=False, label="light",widget=forms.TextInput())
    lepton = forms.IntegerField(required=False, label="lepton",widget=forms.TextInput())
    photon = forms.IntegerField(required=False, label="photon",widget=forms.TextInput())